Traceback (most recent call last):
  File "viterbi.py", line 48, in <module>
    getInput()
  File "viterbi.py", line 17, in getInput
    with open(arg[2]) as f:
IOError: [Errno 2] No such file or directory: '/Users/sparshagarwal/OneDrive/Fall'
